import React from "react";
import { Camera } from "lucide-react";
import Input from "../../../components/ui/Input";
import Select from "../../../components/ui/Select";

export const Step1BioData = ({ formData, handleChange, errors = {} }) => {
  const civilStatusOptions = [
    { value: "single", label: "Single" },
    { value: "married", label: "Married" },
    { value: "divorced", label: "Divorced" },
    { value: "widowed", label: "Widowed" },
    { value: "separated", label: "Separated" },
  ];

  const genderOptions = [
    { value: "male", label: "Male" },
    { value: "female", label: "Female" },
    { value: "other", label: "Other" },
  ];

  const religionOptions = [
    { value: "christianity", label: "Christianity" },
    { value: "islam", label: "Islam" },
    { value: "traditional", label: "Traditional" },
    { value: "other", label: "Other" },
  ];

  return (
    <div className="animate-fadeIn">
      <div className="mb-6">
        <h2 className="text-2xl font-bold text-gray-800">Primary Identity</h2>
        <p className="text-gray-500 text-sm mt-1">
          Enter the patient's core biographical data.
        </p>
      </div>

      <div className="flex items-start gap-8 mb-8 pb-8 border-b border-gray-100">
        <div className="flex flex-col items-center gap-3">
          <div className="h-28 w-28 rounded-full bg-indigo-50 border-2 border-dashed border-indigo-200 flex items-center justify-center text-indigo-400 hover:bg-indigo-100 hover:border-indigo-300 transition cursor-pointer relative overflow-hidden group">
            <Camera
              size={32}
              className="group-hover:scale-110 transition-transform"
            />
            <div className="absolute inset-0 bg-black/40 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity">
              <span className="text-white text-xs font-medium">Upload</span>
            </div>
          </div>
        </div>

        <div className="flex-1 grid grid-cols-2 gap-5">
          <Input
            label="Patient ID (PID)"
            name="pid"
            value={formData.pid}
            placeholder="Auto-generated"
            readOnly
            helperText="Auto-generated by backend"
          />
          <Select
            label="Civil Status"
            name="civilStatus"
            value={formData.civilStatus}
            onChange={handleChange}
            options={civilStatusOptions}
            error={errors.civilStatus}
          />
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
        <Input
          label="Last Name"
          name="lastName"
          value={formData.lastName}
          onChange={handleChange}
          placeholder="e.g. Lasisi"
          error={errors.lastName}
          required
        />
        <Input
          label="First Name"
          name="firstName"
          value={formData.firstName}
          onChange={handleChange}
          placeholder="e.g. Fatima"
          error={errors.firstName}
          required
        />
        <Input
          label="Other Names"
          name="otherNames"
          value={formData.otherNames}
          onChange={handleChange}
          placeholder="Optional"
          error={errors.otherNames}
        />
      </div>

      <div className="grid grid-cols-1 md:grid-cols-4 gap-5 mt-5">
        <Input
          label="Date of Birth"
          name="dob"
          type="date"
          value={formData.dob}
          onChange={handleChange}
          error={errors.dob}
          required
        />
        <Input
          label="Age"
          name="age"
          value={formData.age}
          placeholder="Auto-calculated"
          readOnly
          helperText="Calculated from date of birth"
        />
        <Select
          label="Gender"
          name="gender"
          value={formData.gender}
          onChange={handleChange}
          options={genderOptions}
          error={errors.gender}
          required
        />
        <Input
          label="Nationality"
          name="nationality"
          value={formData.nationality}
          onChange={handleChange}
          placeholder="e.g. Nigerian, Ghanaian"
          error={errors.nationality}
        />
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-5 mt-5">
        <Input
          label="Tribe (Optional)"
          name="tribe"
          value={formData.tribe}
          onChange={handleChange}
          placeholder="e.g. Yoruba, Igbo"
          error={errors.tribe}
        />
        <Select
          label="Religion"
          name="religion"
          value={formData.religion}
          onChange={handleChange}
          options={religionOptions}
          error={errors.religion}
        />
      </div>
    </div>
  );
};
