import { useEffect, useState } from "react";
import { PackageCheck, RefreshCw } from "lucide-react";
import { toast } from "react-toastify";
import { api } from "../../utils/api";

const blank = { quantity: "", unit: "", batch_number: "", expiry_date: "", notes: "" };

export default function MedicationWorklist() {
  const [orders, setOrders] = useState([]); const [loading, setLoading] = useState(true); const [activeItem, setActiveItem] = useState(null); const [form, setForm] = useState(blank);
  const load = async () => { setLoading(true); try { setOrders(await api.get("/orders/worklist/medication")); } catch (error) { toast.error(error.message || "Could not load medication orders"); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const open = (order, item) => { setActiveItem({ ...item, patient_name: order.patient_name, order_number: order.order_number }); setForm(blank); };
  const change = (event) => setForm((old) => ({ ...old, [event.target.name]: event.target.value }));
  const dispense = async (event) => { event.preventDefault(); if (!activeItem) return; try { await api.post(`/medications/order-items/${activeItem.id}/dispenses`, { ...form, quantity: Number(form.quantity), expiry_date: form.expiry_date || null, batch_number: form.batch_number || null, notes: form.notes || null }); toast.success("Medication dispensed"); setActiveItem(null); await load(); } catch (error) { toast.error(error.message || "Could not record dispensing"); } };
  return <main className="flex-1 overflow-auto p-4 md:p-6"><header className="mb-7 flex justify-between gap-4"><div><h1>Pharmacy worklist</h1><p>Dispense medication only against an approved medication order.</p></div><button className="btn btn-secondary" onClick={load}><RefreshCw size={16}/> Refresh</button></header><div className="grid grid-cols-1 xl:grid-cols-3 gap-5"><section className="card elevated p-5 xl:col-span-2"><h2 className="text-lg mb-4">Medication orders</h2>{loading ? <p>Loading…</p> : orders.length ? <div className="space-y-3">{orders.map((order) => <div key={order.id} className="border rounded-lg p-4"><div className="flex justify-between gap-3"><div><b>{order.patient_name}</b><p className="text-sm">{order.order_number} · {order.admission_id ? "Inpatient" : "Outpatient"}</p></div><span className={`badge ${order.priority === "stat" ? "badge-danger" : order.priority === "urgent" ? "badge-warning" : "badge-primary"}`}>{order.priority}</span></div><div className="mt-3 space-y-2">{order.items.filter((item) => item.status !== "cancelled").map((item) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-2 bg-slate-50 p-3 rounded"><span><b>{item.name}</b>{item.details_json?.dose ? ` · ${item.details_json.dose}` : ""}</span><button className="btn btn-primary btn-small" onClick={() => open(order, item)}><PackageCheck size={15}/> Dispense</button></div>)}</div></div>)}</div> : <p>No active medication orders.</p>}</section><section className="card elevated p-5">{activeItem ? <><h2 className="text-lg">Dispense medication</h2><p className="text-sm mb-4"><b>{activeItem.patient_name}</b><br/>{activeItem.name} · {activeItem.order_number}</p><form onSubmit={dispense} className="space-y-3"><input required type="number" step="any" min="0.01" className="input-field w-full" name="quantity" value={form.quantity} onChange={change} placeholder="Quantity"/><input required className="input-field w-full" name="unit" value={form.unit} onChange={change} placeholder="Unit, e.g. tablets or mL"/><input className="input-field w-full" name="batch_number" value={form.batch_number} onChange={change} placeholder="Batch number (optional)"/><label className="text-sm">Expiry date<input type="date" className="input-field w-full mt-1" name="expiry_date" value={form.expiry_date} onChange={change}/></label><textarea className="input-field w-full" name="notes" value={form.notes} onChange={change} placeholder="Dispensing notes"/><button className="btn btn-primary w-full"><PackageCheck size={16}/> Confirm dispense</button></form></> : <div className="min-h-64 flex items-center justify-center text-center text-gray-500">Choose an order item to dispense.</div>}</section></div></main>;
}
