import React, { useState, useEffect } from "react";
import StepOne from "./StepOne";
import StepTwo from "./StepTwo";
import StepThree from "./StepThree";
import StepFour from "./StepFour";
import { toast } from "react-toastify";
import {
  validateStep1,
  validateStep2,
  validateStep3,
  validateStep4,
} from "../../utils/registrationValidation";
import { useRegistrationStore } from "../../store/RegistrationStore";

const RegistrationForm = () => {
  const [step, setStep] = useState(1);
  const [errors, setErrors] = useState({});
  const [submitStatus, setSubmitStatus] = useState({
    type: "idle",
    message: "",
  });
  const [formData, setFormData] = useState({
    // Step 1: Bio Data
    lastName: "",
    firstName: "",
    otherNames: "",
    pid: "", // Auto-generated by backend on submit
    passport: null,
    tribe: "",
    religion: "",
    gender: "",
    dob: "",
    age: "",
    nationality: "Nigerian",
    civilStatus: "",
    // Step 2 Contact & Location
    phone: "",
    altPhone: "",
    email: "",
    address: "",
    state: "",
    lga: "",
    // Step 3: Statutory & Socio-Economic
    nin: "",
    nhisNumber: "",
    militaryNumber: "",
    education: "",
    regDate: new Date().toISOString().split("T")[0], // Auto-filled with current date
    regBy: "Faith Peace", // This would ideally come from the logged-in user context

    // Step 4:
    nokName: "",
    nokPhone: "",
    nokRelationship: "",
    nokAddress: "",
  });

  // Handle input changes for all steps
  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => {
      const next = { ...prev, [name]: value };
      if (name === "state") next.lga = ""; // Clear LGA when state changes
      return next;
    });
  };

  // To calculate age from DOB
  useEffect(() => {
    if (formData.dob) {
      const birthDate = new Date(formData.dob);
      const today = new Date();
      let age = today.getFullYear() - birthDate.getFullYear();
      const m = today.getMonth() - birthDate.getMonth();
      if (m < 0 || (m === 0 && today.getDate() < birthDate.getDate())) {
        age--;
      }
      setFormData((prev) => ({ ...prev, age: age > 0 ? age : 0 }));
    }
  }, [formData.dob]);

  const prevStep = () => {
    setErrors({});
    setStep((s) => s - 1);
  };

  const handleNextStep = () => {
    let result = { valid: false, errors: {} };
    if (step === 1) result = validateStep1(formData);
    else if (step === 2) result = validateStep2(formData);
    else if (step === 3) result = validateStep3(formData);
    if (!result.valid) {
      setErrors(result.errors);
      toast.error("Please fix the errors before continuing");
      return;
    }
    setErrors({});
    setStep((s) => s + 1);
  };

  const handleFinishClick = () => {
    const result = validateStep4(formData);
    if (!result.valid) {
      setErrors(result.errors);
      toast.error("Please fix the errors before submitting");
      return;
    }
    setErrors({});
    handleSubmit({ preventDefault: () => {} });
  };

  const [isSubmitting, setIsSubmitting] = useState(false);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setIsSubmitting(true);
    setSubmitStatus({
      type: "pending",
      message: "Submitting patient registration...",
    });
    try {
      // populate zustand store and use its submit action (which validates with Zod)
      const { setFormData: syncFormData, submit } =
        useRegistrationStore.getState();
      console.log("[RegistrationForm] payload before store sync:", formData);
      syncFormData(formData);
      const result = await submit();
      console.log("[RegistrationForm] submit result:", result);
      if (!result.success) {
        const validationDetails = result.errors
          ? JSON.stringify(result.errors)
          : null;
        const networkDetails = result.error
          ? result.error.status
            ? `${result.error.message} (HTTP ${result.error.status})`
            : result.error.message
          : null;
        throw (
          result.error ||
          new Error(
            validationDetails || networkDetails || "Registration failed",
          )
        );
      }
      const patient = result.data;
      setSubmitStatus({
        type: "success",
        message: patient?.pid
          ? `Saved successfully as ${patient.pid}`
          : "Saved successfully",
      });
      toast.success(
        patient?.pid
          ? `Patient ${patient.pid} (${formData.firstName} ${formData.lastName}) registered successfully!`
          : `Patient ${formData.firstName} ${formData.lastName} registered successfully!`,
      );
      syncFormData({
        lastName: "",
        firstName: "",
        otherNames: "",
        pid: "",
        dob: "",
        age: "",
        gender: "",
        civilStatus: "",
        religion: "",
        tribe: "",
        phone: "",
        altPhone: "",
        email: "",
        address: "",
        state: "",
        lga: "",
        nin: "",
        nhisNumber: "",
        militaryNumber: "",
        education: "",
        occupation: "",
        nokName: "",
        nokPhone: "",
        nokRelationship: "",
        nokAddress: "",
      });
      setStep(1);
    } catch (err) {
      console.error("[RegistrationForm] registration error:", err);
      setSubmitStatus({
        type: "error",
        message: err?.status
          ? `${err.message} (HTTP ${err.status})`
          : err?.message || "Registration failed",
      });
      toast.error(err.message || "Registration failed");
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
      {/* Progress Bar */}
      <div className="bg-gray-50 px-8 py-4 border-b border-gray-100 flex justify-between items-center">
        <div>
          <h2 className="text-lg font-bold text-gray-800">Step {step} of 4</h2>
          <p className="text-sm text-gray-500">
            {step === 1 && "Primary identity and Bio-data"}
            {step === 2 && "Contact & Location"}
            {step === 3 && "Statutory & Socio-Economic"}
            {step === 4 && "Next of Kin"}
          </p>
        </div>
        <div className="flex gap-2">
          {[1, 2, 3, 4].map((num) => (
            <div
              key={num}
              className={`h-2 w-12 rounded-full transition-all ${step >= num ? "bg-blue-600" : "bg-gray-200"}`}
            ></div>
          ))}
        </div>
      </div>

      {submitStatus.type !== "idle" && (
        <div
          className={`mx-8 mt-4 rounded-lg border px-4 py-3 text-sm ${
            submitStatus.type === "success"
              ? "border-green-200 bg-green-50 text-green-700"
              : submitStatus.type === "error"
                ? "border-red-200 bg-red-50 text-red-700"
                : "border-blue-200 bg-blue-50 text-blue-700"
          }`}
        >
          {submitStatus.message}
        </div>
      )}

      <div className="p-8">
        {/* Render Steps */}
        {step === 1 && (
          <StepOne
            formData={formData}
            handleChange={handleChange}
            errors={errors}
          />
        )}
        {step === 2 && (
          <StepTwo
            formData={formData}
            handleChange={handleChange}
            errors={errors}
          />
        )}
        {step === 3 && (
          <StepThree
            formData={formData}
            handleChange={handleChange}
            errors={errors}
          />
        )}
        {step === 4 && (
          <StepFour
            formData={formData}
            handleChange={handleChange}
            errors={errors}
          />
        )}

        {/* Navigation */}
        <div className="mt-10 flex justify-between items-center border-t border-gray-300 pt-6">
          <button
            type="button"
            onClick={prevStep}
            disabled={step === 1}
            className={`px-6 py-2 bg-gray-200 rounded-lg font-medium transition-all ${step === 1 ? "text-gray-300 cursor-not-allowed" : "text-gray-600 hover:bg-gray-300"}`}
          >
            Previous
          </button>

          {step === 4 ? (
            <button
              type="button"
              onClick={handleFinishClick}
              disabled={isSubmitting}
              className="bg-green-600 text-white px-10 py-2 rounded-lg font-bold hover:bg-green-700 disabled:opacity-50 shadow-lg shadow-green-200 transition-all flex items-center gap-2"
            >
              {isSubmitting ? "Registering..." : "Finish and Register"}
            </button>
          ) : (
            <button
              type="button"
              onClick={handleNextStep}
              className="bg-blue-600 text-white px-10 py-2 rounded-lg font-bold hover:bg-blue-700 shadow-blue-200 transition-all"
            >
              Next Step
            </button>
          )}
        </div>
      </div>
    </div>
  );
};

export default RegistrationForm;
