import { useEffect, useMemo, useState } from "react";
import { ClipboardPenLine, RefreshCw, Save } from "lucide-react";
import { toast } from "react-toastify";
import { api } from "../../utils/api";

export default function ClinicalForms() {
  const [templates, setTemplates] = useState([]); const [templateId, setTemplateId] = useState(""); const [patientId, setPatientId] = useState(""); const [visitId, setVisitId] = useState(""); const [admissionId, setAdmissionId] = useState(""); const [values, setValues] = useState({}); const [loading, setLoading] = useState(true);
  const selected = useMemo(() => templates.find((template) => template.id === templateId), [templates, templateId]);
  const load = async () => { setLoading(true); try { const rows = await api.get("/clinical-forms/templates"); setTemplates(rows); if (!templateId && rows[0]) setTemplateId(rows[0].id); } catch (error) { toast.error(error.message || "Could not load specialty templates"); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const select = (event) => { setTemplateId(event.target.value); setValues({}); };
  const change = (event) => setValues((old) => ({ ...old, [event.target.name]: event.target.type === "checkbox" ? event.target.checked : event.target.value }));
  const save = async (status) => { if (!selected) return; if (!patientId || (!visitId && !admissionId)) return toast.error("Patient ID and a visit or admission ID are required"); try { await api.post("/clinical-forms/responses", { template_id: selected.id, patient_id: patientId, visit_id: visitId || null, admission_id: admissionId || null, response_json: values, status }); toast.success(status === "final" ? "Clinical form finalized" : "Clinical form saved as draft"); setValues({}); } catch (error) { toast.error(error.message || "Could not save clinical form"); } };
  const fields = selected?.schema_json?.fields || [];
  return <main className="flex-1 overflow-auto p-4 md:p-6"><header className="mb-7 flex justify-between gap-4"><div><h1>Specialty clinical forms</h1><p>Complete the department-specific template for a visit or admission.</p></div><button className="btn btn-secondary" onClick={load}><RefreshCw size={16}/> Refresh</button></header><section className="card elevated p-5 max-w-5xl"><div className="grid grid-cols-1 md:grid-cols-2 gap-3 mb-5"><label className="text-sm font-medium">Template<select className="input-field w-full mt-1" value={templateId} onChange={select}><option value="">Select template</option>{templates.map((template) => <option key={template.id} value={template.id}>{template.name}{template.department_name ? ` · ${template.department_name}` : ""}</option>)}</select></label><label className="text-sm font-medium">Patient ID / PID<input className="input-field w-full mt-1" value={patientId} onChange={(event) => setPatientId(event.target.value)} placeholder="Patient ID / PID"/></label><label className="text-sm font-medium">Visit ID (outpatient)<input className="input-field w-full mt-1" value={visitId} onChange={(event) => setVisitId(event.target.value)} placeholder="Optional when admission is supplied"/></label><label className="text-sm font-medium">Admission ID (inpatient)<input className="input-field w-full mt-1" value={admissionId} onChange={(event) => setAdmissionId(event.target.value)} placeholder="Optional when visit is supplied"/></label></div>{loading ? <p>Loading templates…</p> : selected ? <><div className="border-t pt-5 grid grid-cols-1 md:grid-cols-2 gap-4">{fields.map((field) => <Field key={field.key} field={field} value={values[field.key]} onChange={change}/>)}</div><div className="flex gap-2 mt-6"><button className="btn btn-secondary" onClick={() => save("draft")}><Save size={16}/> Save draft</button><button className="btn btn-primary" onClick={() => save("final")}><ClipboardPenLine size={16}/> Finalize form</button></div></> : <p>No clinical form templates are configured yet. An administrator can add them in the template setup module.</p>}</section></main>;
}

function Field({ field, value, onChange }) {
  const type = field.type || "text"; const label = `${field.label || field.key}${field.required ? " *" : ""}`;
  if (type === "textarea") return <label className="text-sm font-medium md:col-span-2">{label}<textarea required={field.required} className="input-field w-full mt-1 min-h-24" name={field.key} value={value || ""} onChange={onChange}/></label>;
  if (type === "select") return <label className="text-sm font-medium">{label}<select required={field.required} className="input-field w-full mt-1" name={field.key} value={value || ""} onChange={onChange}><option value="">Select</option>{(field.options || []).map((option) => <option key={option} value={option}>{option}</option>)}</select></label>;
  if (type === "checkbox") return <label className="text-sm font-medium flex items-center gap-2"><input type="checkbox" name={field.key} checked={Boolean(value)} onChange={onChange}/>{label}</label>;
  return <label className="text-sm font-medium">{label}<input required={field.required} className="input-field w-full mt-1" type={type === "number" ? "number" : "text"} name={field.key} value={value || ""} onChange={onChange}/></label>;
}
