import { useEffect, useState } from "react";
import { FileCheck2, RefreshCw } from "lucide-react";
import { toast } from "react-toastify";
import { api } from "../../utils/api";

const blank = { admission_diagnosis: "", discharge_diagnosis: "", hospital_course: "", procedures_performed: "", discharge_medications: "", follow_up_instructions: "", condition_at_discharge: "" };

export default function DischargeSummaries() {
  const [admissions, setAdmissions] = useState([]); const [selected, setSelected] = useState(null); const [form, setForm] = useState(blank); const [summary, setSummary] = useState(null); const [loading, setLoading] = useState(true); const [disposition, setDisposition] = useState("Home");
  const load = async () => { setLoading(true); try { setAdmissions(await api.get("/hospital/admissions")); } catch (error) { toast.error(error.message || "Could not load admissions"); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const select = async (admission) => { setSelected(admission); setSummary(null); setForm(blank); try { const data = await api.get(`/discharge-summaries/admission/${admission.id}`); setSummary(data); setForm({ ...blank, ...data }); } catch (error) { if (error.status !== 404) toast.error(error.message || "Could not load summary"); } };
  const change = (event) => setForm((old) => ({ ...old, [event.target.name]: event.target.value }));
  const save = async (finalize) => { if (!selected) return; try { const data = await api.put(`/discharge-summaries/admission/${selected.id}`, { ...form, finalize }); setSummary(data); toast.success(finalize ? "Discharge summary finalized" : "Draft saved"); } catch (error) { toast.error(error.message || "Could not save summary"); } };
  const discharge = async () => { if (!selected || summary?.status !== "final") return; try { await api.post(`/hospital/admissions/${selected.id}/discharge`, { discharge_disposition: disposition }); toast.success("Patient discharged"); setSelected(null); setSummary(null); setForm(blank); await load(); } catch (error) { toast.error(error.message || "Could not discharge patient"); } };
  const fields = [["admission_diagnosis", "Admission diagnosis", false], ["discharge_diagnosis", "Discharge diagnosis", true], ["hospital_course", "Hospital course", true], ["procedures_performed", "Procedures performed", false], ["discharge_medications", "Discharge medications", false], ["follow_up_instructions", "Follow-up instructions", false], ["condition_at_discharge", "Condition at discharge", false]];
  return <main className="flex-1 overflow-auto p-4 md:p-6"><header className="mb-7 flex justify-between gap-4"><div><h1>Discharge summaries</h1><p>Finalise the clinical summary before discharging an inpatient.</p></div><button className="btn btn-secondary" onClick={load}><RefreshCw size={16}/> Refresh</button></header><div className="grid grid-cols-1 xl:grid-cols-5 gap-5"><section className="card elevated p-4 xl:col-span-2"><h2 className="text-lg mb-4">Admissions</h2>{loading ? <p>Loading…</p> : admissions.filter((row) => row.status === "admitted").length ? admissions.filter((row) => row.status === "admitted").map((row) => <button type="button" key={row.id} onClick={() => select(row)} className={`text-left w-full p-3 rounded-lg border mb-2 ${selected?.id === row.id ? "border-blue-500 bg-blue-50" : "border-slate-200"}`}><b>{row.patient_name || row.patient_id}</b><span className="block text-sm">{row.admission_number} · {row.department_name || "—"}</span></button>) : <p>No active admissions.</p>}</section><section className="card elevated p-5 xl:col-span-3">{selected ? <><div className="flex items-center gap-2 mb-4"><FileCheck2 className="text-blue-700" size={21}/><div><h2 className="text-lg">{selected.patient_name || selected.patient_id}</h2><p className="text-sm">{summary?.status === "final" ? "Final summary — locked" : "Draft summary"}</p></div></div><div className="space-y-3">{fields.map(([name, label, required]) => <label key={name} className="block text-sm font-medium">{label}{required ? " *" : ""}<textarea disabled={summary?.status === "final"} required={required} className="input-field w-full mt-1 min-h-20" name={name} value={form[name] || ""} onChange={change}/></label>)}</div>{summary?.status !== "final" ? <div className="flex gap-2 mt-4"><button className="btn btn-secondary" onClick={() => save(false)}>Save draft</button><button className="btn btn-primary" onClick={() => save(true)}>Finalise summary</button></div> : <div className="mt-5 border-t pt-4"><label className="text-sm">Discharge disposition<input className="input-field w-full mt-1" value={disposition} onChange={(event) => setDisposition(event.target.value)} placeholder="e.g. Home, referral, deceased"/></label><button className="btn btn-primary mt-3" onClick={discharge}>Discharge patient</button></div>}</> : <div className="min-h-64 flex items-center justify-center text-gray-500">Select an admission to prepare the discharge summary.</div>}</section></div></main>;
}
