/**
 * Validation rules for patient registration form.
 * Returns { valid: boolean, errors: { fieldName: string } }
 */

const NAME_REGEX = /^[a-zA-Z\u00C0-\u024F\u1E00-\u1EFF\s\-']+$/;
const NIGERIAN_PHONE_REGEX = /^0[789]\d{9}$/;
const EMAIL_REGEX = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const NIN_REGEX = /^\d{11}$/;
const NHIS_REGEX = /^[a-zA-Z0-9\-]{6,20}$/;

export function validateStep1(formData) {
  const errors = {};

  // PID: auto-generated by backend on submit (no validation needed)

  // Last Name: required, 2-50 chars, letters/spaces/hyphens
  if (!formData.lastName?.trim()) {
    errors.lastName = "Last name is required";
  } else if (formData.lastName.trim().length < 2) {
    errors.lastName = "At least 2 characters required";
  } else if (formData.lastName.trim().length > 50) {
    errors.lastName = "Maximum 50 characters";
  } else if (!NAME_REGEX.test(formData.lastName.trim())) {
    errors.lastName = "Only letters, spaces, hyphens allowed";
  }

  // First Name: required, 2-50 chars
  if (!formData.firstName?.trim()) {
    errors.firstName = "First name is required";
  } else if (formData.firstName.trim().length < 2) {
    errors.firstName = "At least 2 characters required";
  } else if (formData.firstName.trim().length > 50) {
    errors.firstName = "Maximum 50 characters";
  } else if (!NAME_REGEX.test(formData.firstName.trim())) {
    errors.firstName = "Only letters, spaces, hyphens allowed";
  }

  // Other Names: optional, 2-100 if provided
  if (formData.otherNames?.trim()) {
    if (formData.otherNames.trim().length < 2) {
      errors.otherNames = "At least 2 characters if provided";
    } else if (formData.otherNames.trim().length > 100) {
      errors.otherNames = "Maximum 100 characters";
    } else if (!NAME_REGEX.test(formData.otherNames.trim())) {
      errors.otherNames = "Only letters, spaces, hyphens allowed";
    }
  }

  // DOB: required, not future, not > 120 years ago
  if (!formData.dob) {
    errors.dob = "Date of birth is required";
  } else {
    const dob = new Date(formData.dob);
    const today = new Date();
    if (dob > today) {
      errors.dob = "Date of birth cannot be in the future";
    } else {
      const age = today.getFullYear() - dob.getFullYear();
      if (age > 120) {
        errors.dob = "Please enter a valid date of birth";
      }
    }
  }

  // Gender: required
  if (!formData.gender) {
    errors.gender = "Gender is required";
  }

  // Civil Status: required
  if (!formData.civilStatus) {
    errors.civilStatus = "Civil status is required";
  }

  // Nationality: optional, 2-50 if provided
  if (formData.nationality?.trim()) {
    if (formData.nationality.trim().length < 2) {
      errors.nationality = "At least 2 characters if provided";
    } else if (formData.nationality.trim().length > 50) {
      errors.nationality = "Maximum 50 characters";
    }
  }

  // Tribe: optional, 2-50 if provided
  if (formData.tribe?.trim()) {
    if (formData.tribe.trim().length < 2) {
      errors.tribe = "At least 2 characters if provided";
    } else if (formData.tribe.trim().length > 50) {
      errors.tribe = "Maximum 50 characters";
    }
  }

  return { valid: Object.keys(errors).length === 0, errors };
}

export function validateStep2(formData) {
  const errors = {};

  // Primary Phone: required, Nigerian format
  const phone = formData.phone?.replace(/\s/g, "") || "";
  if (!phone) {
    errors.phone = "Primary phone number is required";
  } else if (!NIGERIAN_PHONE_REGEX.test(phone)) {
    errors.phone = "Enter valid Nigerian number (e.g. 08012345678)";
  }

  // Alt Phone: optional, same format if provided
  if (formData.altPhone?.trim()) {
    const alt = formData.altPhone.replace(/\s/g, "");
    if (!NIGERIAN_PHONE_REGEX.test(alt)) {
      errors.altPhone = "Enter valid Nigerian number (e.g. 09012345678)";
    }
  }

  // Email: optional, valid format if provided
  if (formData.email?.trim()) {
    if (!EMAIL_REGEX.test(formData.email.trim())) {
      errors.email = "Enter a valid email address";
    }
  }

  // Address: required, 5-200 chars
  if (!formData.address?.trim()) {
    errors.address = "Residential address is required";
  } else if (formData.address.trim().length < 5) {
    errors.address = "At least 5 characters required";
  } else if (formData.address.trim().length > 200) {
    errors.address = "Maximum 200 characters";
  }

  // State: required
  if (!formData.state) {
    errors.state = "State of residence is required";
  }

  // LGA: required when state selected
  if (formData.state && !formData.lga) {
    errors.lga = "Local Government Area is required";
  }

  return { valid: Object.keys(errors).length === 0, errors };
}

export function validateStep3(formData) {
  const errors = {};

  // NIN: optional, 11 digits if provided
  if (formData.nin?.trim()) {
    const nin = formData.nin.replace(/\s/g, "");
    if (!NIN_REGEX.test(nin)) {
      errors.nin = "NIN must be 11 digits";
    }
  }

  // NHIS: optional, 6-20 alphanumeric if provided
  if (formData.nhisNumber?.trim()) {
    if (!NHIS_REGEX.test(formData.nhisNumber.trim())) {
      errors.nhisNumber = "6–20 characters (letters, numbers, hyphens)";
    }
  }

  // Occupation: optional, 2-100 if provided (from formData.occupation)
  if (formData.occupation?.trim()) {
    if (formData.occupation.trim().length < 2) {
      errors.occupation = "At least 2 characters if provided";
    } else if (formData.occupation.trim().length > 100) {
      errors.occupation = "Maximum 100 characters";
    }
  }

  return { valid: Object.keys(errors).length === 0, errors };
}

export function validateStep4(formData) {
  const errors = {};

  // NOK Name: required, 2-100 chars
  if (!formData.nokName?.trim()) {
    errors.nokName = "Next of kin name is required";
  } else if (formData.nokName.trim().length < 2) {
    errors.nokName = "At least 2 characters required";
  } else if (formData.nokName.trim().length > 100) {
    errors.nokName = "Maximum 100 characters";
  } else if (!NAME_REGEX.test(formData.nokName.trim())) {
    errors.nokName = "Only letters, spaces, hyphens allowed";
  }

  // NOK Relationship: required
  if (!formData.nokRelationship) {
    errors.nokRelationship = "Relationship is required";
  }

  // NOK Phone: required, Nigerian format
  const nokPhone = formData.nokPhone?.replace(/\s/g, "") || "";
  if (!nokPhone) {
    errors.nokPhone = "Next of kin phone is required";
  } else if (!NIGERIAN_PHONE_REGEX.test(nokPhone)) {
    errors.nokPhone = "Enter valid Nigerian number (e.g. 08011122233)";
  }

  // NOK Address: required, 5-200 chars
  if (!formData.nokAddress?.trim()) {
    errors.nokAddress = "Next of kin address is required";
  } else if (formData.nokAddress.trim().length < 5) {
    errors.nokAddress = "At least 5 characters required";
  } else if (formData.nokAddress.trim().length > 200) {
    errors.nokAddress = "Maximum 200 characters";
  }

  return { valid: Object.keys(errors).length === 0, errors };
}
